### ISSUE TITLE
Null reference when a client closes.

### ISSUE THREAD

**Issue by robbgray** [nykwil/UnityGGPO#1]
When GGPO called Vw_load_game_state_callback, GameState.FromBytes threw an error when it tried to convert NativeArray<byte> to Array. This happened in both my game and your VectorWar. I tested save/load states manually and there is no problem.

I can produce this error on VectorWar by closing VectorWar.exe while it's connected to the editor.

**Comment by hifight** [comment]
Additional note. The same error happened in my game without having to close the client. When GGPO is trying to rollback, Vw_load_game_state_callback gets called and caused the same error. After that GGPO returns ERRORCODE_IN_ROLLBACK every frame.

**Comment by hifight** [comment]
I'm not 100% sure if this is the right thing to do but I fixed this problem by adding SetAtomicSafetyHandle to Helper.ToArray (using information from this thread https://forum.unity.com/threads/converting-a-computebuffer-to-a-nativearray.722651/)

    unsafe public static NativeArray<byte> ToArray(void* dataPointer, int length) {
        unsafe {
            var array = NativeArrayUnsafeUtility.ConvertExistingDataToNativeArray<byte>(dataPointer, length, Allocator.Persistent);
#if ENABLE_UNITY_COLLECTIONS_CHECKS
            NativeArrayUnsafeUtility.SetAtomicSafetyHandle(ref array, AtomicSafetyHandle.Create());
#endif
            return array;
        }
    }

**Comment by nykwil** [comment]
This looks good I'll check that in. Also random but instead of building a client each time you can actually open to copies of Unity with the same assets as long as they have different Libraries. I create a symbolic link of the Asset folder into a new folder. mklink /D .\UnityGGPO\Assets\ .\UnityGGPOClone\Assets\
