### ISSUE TITLE
Lot's of errors on import from Entities libraries - Unity version 2021.3.f1 LTS

### ISSUE THREAD

**Issue by sharpaccent** [nykwil/UnityGGPO#11]
Hi
When I import the project to latest unity i get lots off errors all coming from Library/PackageCache/com.unity.entities@0.50.1 etc 

The errors are: 
Library\PackageCache\com.unity.entities@0.50.1-preview.2\Unity.Entities\DefaultWorld.cs(26,25): error CS0117: 'JobsUtility' does not contain a definition for 'ClearSystemIds'
Library\PackageCache\com.unity.entities@0.50.1-preview.2\Unity.Entities\EntityManager.cs(221,29): error CS0117: 'JobsUtility' does not contain a definition for 'PanicFunction'
Library\PackageCache\com.unity.entities@0.50.1-preview.2\Unity.Entities\EntityManager.cs(223,29): error CS0117: 'JobsUtility' does not contain a definition for 'PanicFunction'
Library\PackageCache\com.unity.entities@0.50.1-preview.2\Unity.Entities\SystemDependencySafetyUtility.cs(64,53): error CS0117: 'JobsUtility' does not contain a definition for 'GetSystemIdMappings'
Library\PackageCache\com.unity.entities@0.50.1-preview.2\Unity.Entities\SystemState.cs(416,50): error CS0117: 'JobsUtility' does not contain a definition for 'GetSystemIdCellPtr'

Any clue how to solve this? I tried upgrading and downgrading the entities package to multiple versions but to no avail. 
Thanks

**Comment by nykwil** [comment]
Yeah DOTS 0.50 only works with 2020 LTS. If this has changed can you point me to the post I can't find much info on 0.50.1

**Comment by sharpaccent** [comment]
I can only find this https://forum.unity.com/threads/notice-on-dots-compatibility-with-unity-2021-1.1091800/#:~:text=With%20the%20release%20of%20Unity,entire%20entities%20suite%20is%20not. so I assume it's only available for 2020 LTS right?
