### ISSUE TITLE
GGPO keeps port ip open after crash.

### ISSUE THREAD

**Issue by robbgray** [nykwil/UnityGGPO#2]
There is a problem when GGPO session isn't ended properly (due to error etc.), you cannot use the same ip+port again and have to restart Unity editor.

**Comment by hakansanli** [comment]
I've had this same issue with with unreal engine too, it's a problem with ggpo not with this wrapper. It looks like a problem when debugging but in reality it's not a problem. If you're in a build game, an if check on GGPO.Session.ggpo is Intptr.zero and doing close session if not equal before starting a session will fix. in case of crashes, when the app closes, the port is free. This is only problem when you use an editor that cleans singletons but doesn't release them, like the unity/unreal development editor.

**Comment by nykwil** [comment]
This issue is fixed now.
