### ISSUE TITLE
AdvanceFrame callback will nullify 'this' pointer

### ISSUE THREAD

**Issue by supermoosefgc** [nykwil/UnityGGPO#3]
I ran into a weird issue where 'this' would be null when the AdvanceFrame callback is executed. I'm not sure if this is just undefined behavior or a bug, as the VectorWar demo uses static methods for all of the delegates it passes to GGPO.Session.StartSession()

I was able to fix the issue by making all of the delegate callbacks static methods, and just using a static 'self' variable to call the instance methods that needed to be executed. 

It might just be a caveat of interop with .net, but I thought I'd give you a heads up  anyway :)

**Comment by nykwil** [comment]
I fixed this issue. Eventually the delgate would get moved. It's fixed now with marshalling. I can't believe I didn't see this until now sorry.
