### ISSUE TITLE
Hard windows dependecies?

### ISSUE THREAD

**Issue by RedDude** [nykwil/UnityGGPO#6]
Hi.
Thanks for the UnityGGPO, is really hard to find ggpo information related with unity;

I manage to use UnityGGPO just fine in my machine. however, when execute the vectorwars to other computers. 
Unity doesn't find the unityGGPO. I was only able to get it working just after installing the vcruntime.

So it means that UnityGGPO/GGPO was a hard dependency with windows and I will be unable to have my game working when playing in other plataforms (ie. nintendo switch)?

Thanks

**Comment by nykwil** [comment]
This is a restriction of ggpo and less a restriction off the wrapper I wrote. There is a crossplatform version of ggpo and I think it works but none of the pull requests have been accepted so you'll probably have to look at a fork to get it working. I would also like to get this working for other platforms so if you do investigate the crossplatform branch of ggpo please report back. Writting the wrapper for other platforms should be trivial.
