### ISSUE TITLE
MarshalDirectiveException

### ISSUE THREAD

**Issue by soulos90** [nykwil/UnityGGPO#7]
Hi, I assume this is probably just a me issue, but I am getting the error: 
"MarshalDirectiveException: The type `System.Object' layout needs to be Sequential or Explicit"
at:
"GGPO.StartSession (System.IntPtr& session, System.IntPtr beginGame, System.IntPtr advanceFrame, System.IntPtr loadGameState, System.IntPtr logGameState, System.IntPtr saveGameState, System.IntPtr freeBuffer, System.IntPtr onEvent, System.String game, System.Int32 num_players, System.Int32 localport) (at Assets/UnityGGPO/Scripts/GGPO.cs:240)"

The reason I bring this up to you is using unityggpo the way it is in vectorwar the marshaler is only called in ggpo.session and the .dll built in c++ so I don't see how what I pass into it could be causing this. Also I structured all my callbacks to try and look like the VectorWar ones, and checked the layout of all the pointers I pass into startsession and they are all sequential or explicit. 

I also tried futsing with vectorwar to get it to throw this issue to give me some insight into what about my project needs to change to fit this tool to no avail.

If you have any insight into what could be freaking out our good friend Marshal I would be eternally grateful.

**Comment by nykwil** [comment]
I think you're just not using statics. There's a session style access and I
updated the example to use session style where you don't have to pass raw
pointers and can use unity ggpo without needing "unsafe" code.

Also the development branch has a pretty major update to the vector war
example that I might move to main soion, if that matters (the api is still
pretty much the same).

**Comment by soulos90** [comment]
I ended up avoiding the issue by using a copy of vectorwar and just rewriting it, so it must be something like what you said (though for the life of me I couldn't find a difference). If I get more info I'll update this but I'm all good now.
Thanks for the response!
