### ISSUE TITLE
Problems with Setup

### ISSUE THREAD

**Issue by JamesThomason** [nykwil/UnityGGPO#8]
I'm having trouble getting the dll in my project. Where exactly should the repo be on my machine in order to get the dll to be built into my project's plugin folder? And do I need to actually run INSTALL? Because I can only seem to build it, when I try to run it I get an access denied error.

**Comment by nykwil** [comment]
I've included a prebuilt dll in the Assets\UnityGGPO\Plugins\Windows\x86_64 folder. If you are building your own dll you can overwrite that one. What changes are you making to the dll?

**Comment by nykwil** [comment]
If you figure out why the INSTALL project isn't working properly let me know, I'll update it.

**Comment by JamesThomason** [comment]
I'm haven't made any changes, I'm just trying to follow the readme instructions.
I've put the pre-built dll in my project in the same place as the example project, but I personally don't have a lot of experience using them. I think need to add it to the project dependencies somehow? I'm really not great at cmd-level coding. I'm more of a scripter tbh.

**Comment by JamesThomason** [comment]
Yeah that worked out much better for me, thanks!
